<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="page-heading heading-actions"><div><p class="eyebrow">BUKU REGISTER DIGITAL</p><h1>Dokumen Masuk</h1><p>Kelola dokumen berdasarkan pengirim, tanggal, jenis, jumlah, dan ekspedisi.</p></div><a href="<?= site_url('dokumen-masuk/tambah') ?>" class="btn btn-primary" data-open-input-modal>＋ Tambah dokumen</a></section>

<section class="panel filter-panel"><form method="get" action="<?= site_url('dokumen-masuk') ?>" class="filter-form">
    <div class="form-group search-group"><label for="q">Cari dokumen</label><div class="input-with-icon"><span>⌕</span><input id="q" type="search" name="q" value="<?= esc($filters['keyword']) ?>" placeholder="Pengirim, perihal, penerima, jenis..."></div></div>
    <div class="form-group"><label for="jenis">Jenis</label><select id="jenis" name="jenis"><option value="">Semua jenis</option><?php foreach ($jenisOptions as $option): ?><option value="<?= esc($option) ?>" <?= $filters['jenis'] === $option ? 'selected' : '' ?>><?= esc($option) ?></option><?php endforeach ?></select></div>
    <div class="form-group"><label for="dari">Dari tanggal diterima</label><input id="dari" type="date" name="dari" value="<?= esc($filters['from']) ?>"></div>
    <div class="form-group"><label for="sampai">Sampai tanggal diterima</label><input id="sampai" type="date" name="sampai" value="<?= esc($filters['to']) ?>"></div>
    <input type="hidden" name="per_page" value="<?= $filters['perPage'] ?>">
    <div class="filter-actions"><button type="submit" class="btn btn-secondary">Terapkan</button><a href="<?= site_url('dokumen-masuk') ?>" class="btn btn-ghost">Reset</a></div>
</form></section>

<section class="panel register-panel"><div class="table-wrap"><table><thead><tr><th>No.</th><th>Pengirim</th><th>Perihal</th><th>Penerima</th><th>Hari</th><th>Tanggal Diterima</th><th>Pengambilan</th><th>Aksi</th></tr></thead><tbody>
<?php if ($dokumen === []): ?><tr><td colspan="8"><div class="empty-state"><span>⌕</span><strong>Data tidak ditemukan</strong><p>Ubah filter atau tambahkan dokumen masuk baru.</p><a href="<?= site_url('dokumen-masuk/tambah') ?>" class="btn btn-primary btn-sm" data-open-input-modal>Tambah dokumen</a></div></td></tr>
<?php else: ?><?php $rowNumber = (($pager->getCurrentPage('dokumen_masuk') - 1) * $filters['perPage']) + 1; ?><?php foreach ($dokumen as $row): ?><tr><td><strong><?= $rowNumber++ ?></strong></td><td><strong><?= esc($row['pengirim']) ?></strong></td><td class="cell-wrap"><?= esc($row['perihal'] ?: '-') ?></td><td><?= esc($row['penerima'] ?: '-') ?></td><td><?= esc($row['hari']) ?></td><td><?= date('d-m-Y', strtotime($row['tanggal'])) ?></td><td><span class="pickup-status <?= $row['pengambilan'] ? 'completed' : 'pending' ?>" title="<?= esc($row['pengambilan'] ?: 'Belum diambil', 'attr') ?>"><?= esc($row['pengambilan'] ?: 'Belum diambil') ?></span></td><td><div class="table-actions"><a class="icon-btn" href="<?= site_url('dokumen-masuk/' . $row['id']) ?>" title="Detail" data-open-detail-modal data-detail-url="<?= site_url('dokumen-masuk/' . $row['id']) ?>">⌕</a><a class="icon-btn" href="<?= site_url('dokumen-masuk/' . $row['id'] . '/ubah') ?>" title="Ubah" data-open-edit-modal data-detail-url="<?= site_url('dokumen-masuk/' . $row['id']) ?>">✎</a><button class="icon-btn icon-btn-delete" type="button" title="Hapus" data-open-delete-modal data-delete-url="<?= site_url('dokumen-masuk/' . $row['id'] . '/hapus') ?>" data-delete-label="Dokumen dari <?= esc($row['pengirim'], 'attr') ?>" data-delete-locked="<?= trim((string) $row['pengambilan']) !== '' ? '1' : '0' ?>">×</button></div></td></tr><?php endforeach ?><?php endif ?>
</tbody></table></div><div class="table-list-footer"><form method="get" action="<?= site_url('dokumen-masuk') ?>" class="table-length-form"><input type="hidden" name="q" value="<?= esc($filters['keyword']) ?>"><input type="hidden" name="jenis" value="<?= esc($filters['jenis']) ?>"><input type="hidden" name="dari" value="<?= esc($filters['from']) ?>"><input type="hidden" name="sampai" value="<?= esc($filters['to']) ?>"><label for="dokumen_per_page">Tampilkan</label><select id="dokumen_per_page" name="per_page" aria-label="Jumlah baris per halaman" data-table-length><?php foreach ([10, 20, 50, 100] as $size): ?><option value="<?= $size ?>" <?= $filters['perPage'] === $size ? 'selected' : '' ?>><?= $size ?></option><?php endforeach ?></select><span>data</span></form><?php if ($dokumen !== []): ?><div class="pagination-wrap"><?= $pager->links('dokumen_masuk', 'default_full') ?></div><?php endif ?></div></section>
<?= $this->endSection() ?>
