<?php

namespace App\Libraries;

use RuntimeException;
use SimpleXMLElement;
use ZipArchive;

/** Reads calculated figures from a workpaper generated by Simulasi Hitung. */
final class LrWorkpaperImportParser
{
    private const NS = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
    private const OFFICE_REL_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
    private const REL_NS = 'http://schemas.openxmlformats.org/package/2006/relationships';

    public const RULE = 'simulasi_kertas_kerja_v1';
    public const UNITS = [
        'Korporat Kanwil' => 'KORPORAT KANWIL',
        'Kanwil' => 'KANWIL',
        'Surabaya' => 'SURABAYA',
        'Kediri' => 'KEDIRI',
        'Malang' => 'MALANG',
        'Madiun' => 'MADIUN',
        'Banyuwangi' => 'BANYUWANGI',
    ];
    private const COLUMNS = ['L' => 'KUR', 'M' => 'PEN', 'N' => 'NON KUR', 'O' => 'KBG/SURETYSHIP', 'P' => 'KONSUMTIF', 'Q' => 'PRODUKTIF', 'R' => 'TOTAL'];
    // S–X is the "% Pencapaian" table. X is its TOTAL value; S–W are kept so
    // the Corporate view can reveal the same LOB detail as the workpaper.
    private const PERCENTAGE_COLUMNS = ['S' => 'KUR', 'T' => 'PEN', 'U' => 'KBG/SURETYSHIP', 'V' => 'KONSUMTIF', 'W' => 'PRODUKTIF', 'X' => 'TOTAL'];

    /** @return array<string,array<string,mixed>> */
    public function parse(string $path, int $year, int $month, string $basis): array
    {
        if (!extension_loaded('bcmath')) throw new RuntimeException('BCMath diperlukan untuk membaca nominal laporan.');
        if (!is_file($path) || filesize($path) > 5 * 1024 * 1024) throw new RuntimeException('Berkas Excel maksimal 5 MB.');
        if (!in_array($basis, LrRealizationService::BASES, true) || $month < 1 || $month > 12 || $year < 2000 || $year > 2100) {
            throw new RuntimeException('Pilih jenis laporan, bulan, dan tahun yang valid.');
        }

        $zip = new ZipArchive();
        if ($zip->open($path) !== true) throw new RuntimeException('Berkas harus berupa Excel .xlsx hasil Simulasi Hitung yang valid.');
        try {
            $this->validateArchive($zip);
            $strings = $this->sharedStrings($zip);
            $paths = $this->sheetPaths($zip);
            $output = [];
            foreach (self::UNITS as $unit => $sheetName) {
                if (!isset($paths[$sheetName])) throw new RuntimeException('Sheet '.$sheetName.' tidak ditemukan. Gunakan hasil terbaru dari Simulasi Hitung.');
                $cells = $this->sheetCells($zip, $paths[$sheetName], $strings);
                $this->validateMarker($cells, $sheetName, $year, $month, $basis);
                $output[$unit] = $this->readUnit($cells, $unit, $sheetName, $year, $month, $basis);
            }
            return $output;
        } finally {
            $zip->close();
        }
    }

    /** @return array<string,mixed> */
    private function readUnit(array $cells, string $unit, string $sheet, int $year, int $month, string $basis): array
    {
        if (OracleLrSalaryParser::normalizeLabel((string) ($cells['D4']['value'] ?? '')) !== 'uraian'
            || !str_contains(OracleLrSalaryParser::normalizeLabel((string) ($cells['L4']['value'] ?? '')), 'realisasi')) {
            throw new RuntimeException('Format sheet '.$sheet.' bukan Kertas Kerja Simulasi yang dikenali.');
        }

        $values = [];
        $formulaCount = 0;
        $cachedFormulaCount = 0;
        $totalPercentageFormulaCount = 0;
        foreach ($cells as $address => $cell) {
            if (!preg_match('/^[DE](\d+)$/D', $address, $match)) continue;
            $row = (int) $match[1];
            if ($row < 7 || $row > 168) continue;
            // Labels are held in E for detail rows, and D for headings/summary rows.
            if ($address[0] === 'D' && isset($cells['E'.$row]) && trim((string) $cells['E'.$row]['value']) !== '') continue;
            $label = trim((string) $cell['value']);
            if ($label === '') continue;
            $key = $this->labelKey($label);
            if (!$this->isReportLabel($key)) continue;

            $rowValues = [];
            foreach (self::COLUMNS as $column => $name) {
                $number = $cells[$column.$row] ?? null;
                if ($number === null) continue;
                if ($number['formula']) {
                    $formulaCount++;
                    if ($number['value'] !== '') $cachedFormulaCount++;
                }
                // A generated workpaper can legitimately contain a formula whose
                // cached result is still empty, a dash, or an Excel error.  It means
                // the formula has no value to report yet, so preserve the row as zero
                // and let the Laba/Rugi table display it as a dash.
                if ($number['formula'] && ($number['value'] === '' || $number['type'] === 'e' || in_array(trim((string) $number['value']), ['-', '—'], true))) {
                    $rowValues[$name] = '0.00';
                    continue;
                }
                if ($number['value'] === '') continue;
                // A percentage can legitimately be #DIV/0! when its RKA denominator
                // is zero. It must not prevent the already-valid nominal results from
                // being copied into Laba/Rugi.
                if ($name === '%' && $number['type'] === 'e') {
                    $rowValues[$name] = '0.00';
                    continue;
                }
                if (!in_array($number['type'], ['', 'n'], true)) {
                    throw new RuntimeException($sheet.'!'.$column.$row.' harus berisi hasil angka dari rumus Kertas Kerja.');
                }
                try { $rowValues[$name] = LrMoney::decimal((string) $number['value']); }
                catch (\InvalidArgumentException) { throw new RuntimeException($sheet.'!'.$column.$row.' bukan nilai angka yang dapat dibaca.'); }
            }
            $percentageDetails = [];
            if ($unit === 'Korporat Kanwil') {
                foreach (self::PERCENTAGE_COLUMNS as $column => $name) {
                    $number = $cells[$column.$row] ?? null;
                    if ($number === null) continue;
                    if ($name === 'TOTAL' && $number['formula']) {
                        $totalPercentageFormulaCount++;
                    }
                    if ($number['formula'] && ($number['value'] === '' || $number['type'] === 'e' || in_array(trim((string) $number['value']), ['-', '—'], true))) {
                        $percentageDetails[$name] = '0.00';
                        if ($name === 'TOTAL') $rowValues['%'] = '0.00';
                        continue;
                    }
                    if ($number['value'] === '') continue;
                    // A percentage can legitimately be #DIV/0! when its RKA denominator
                    // is zero. Preserve it as zero so the already-valid nominal results
                    // and the remaining percentage details stay available.
                    if ($number['type'] === 'e') {
                        $percentageDetails[$name] = '0.00';
                        if ($name === 'TOTAL') $rowValues['%'] = '0.00';
                        continue;
                    }
                    if (!in_array($number['type'], ['', 'n'], true)) {
                        throw new RuntimeException($sheet.'!'.$column.$row.' harus berisi hasil angka dari rumus Kertas Kerja.');
                    }
                    try { $percentageDetails[$name] = LrMoney::decimal((string) $number['value']); }
                    catch (\InvalidArgumentException) { throw new RuntimeException($sheet.'!'.$column.$row.' bukan nilai angka yang dapat dibaca.'); }
                    if ($name === 'TOTAL') {
                        $rowValues['%'] = $percentageDetails[$name];
                    }
                }
            }
            if ($percentageDetails !== []) $rowValues['percentage_details'] = $percentageDetails;
            if ($rowValues) $values[$key] = $rowValues;
        }
        if ($formulaCount < 20 || !$values) {
            throw new RuntimeException('Rumus pada sheet '.$sheet.' tidak lengkap atau hasil Kertas Kerja tidak dapat dibaca. Buat ulang hasil Simulasi Hitung sebelum di-upload.');
        }
        $hasTotalPercentage = $totalPercentageFormulaCount >= 20;
        return [
            'rule' => self::RULE,
            'unit' => $unit,
            'sheet' => $sheet,
            'year' => $year,
            'month' => $month,
            'basis' => $basis,
            'period' => $basis.' · '.self::monthName($month).' '.$year,
            'values' => $values,
            'percentage_column' => $hasTotalPercentage ? 'X' : null,
            'read_rows' => count($values),
            'calculated_cells' => $cachedFormulaCount,
        ];
    }

    private function validateMarker(array $cells, string $sheet, int $year, int $month, string $basis): void
    {
        $marker = trim((string) ($cells['W1']['value'] ?? ''));
        $expected = 'SIMULASI_LR|'.$basis.'|'.$year.'|'.$month;
        if (!hash_equals($expected, $marker)) {
            throw new RuntimeException('Sheet '.$sheet.' bukan hasil Simulasi Hitung untuk '.$basis.' '.self::monthName($month).' '.$year.'. Buat ulang Kertas Kerja dari menu Simulasi Hitung.');
        }
    }

    private function labelKey(string $label): string
    {
        $key = OracleLrSalaryParser::normalizeLabel($label);
        return match ($key) {
            'imbal jasa profesional - konsultan manajemen (sdm, sop, akuntansi dll)' => 'imbal jasa profesional - konsultan manajemen',
            'tranportasi dinas dalam negeri' => 'transportasi dinas dalam negeri',
            'tranportasi dinas luar negeri' => 'transportasi dinas luar negeri',
            default => $key,
        };
    }

    private function isReportLabel(string $key): bool
    {
        static $labels = null;
        if ($labels === null) {
            $labels = [];
            foreach (LrReportRows::rows() as $row) {
                $labels[$this->labelKey((string) $row['label'])] = true;
                if (isset($row['value_label'])) $labels[$this->labelKey((string) $row['value_label'])] = true;
                foreach ($row['details'] ?? [] as $detail) $labels[$this->labelKey((string) $detail['label'])] = true;
            }
        }
        return isset($labels[$key]);
    }

    /** @return array<string,string> */
    private function sheetPaths(ZipArchive $zip): array
    {
        $workbook = $this->xml($zip, 'xl/workbook.xml');
        $rels = $this->xml($zip, 'xl/_rels/workbook.xml.rels');
        $relationshipTargets = [];
        foreach ($rels->children(self::REL_NS) as $relation) {
            $attributes = $relation->attributes();
            if ((string) $attributes['TargetMode'] === 'External') throw new RuntimeException('Tautan eksternal tidak didukung.');
            $relationshipTargets[(string) $attributes['Id']] = (string) $attributes['Target'];
        }
        $workbook->registerXPathNamespace('s', self::NS);
        $paths = [];
        foreach ($workbook->xpath('//s:sheets/s:sheet') as $sheet) {
            $name = strtoupper((string) $sheet['name']);
            $id = (string) $sheet->attributes(self::OFFICE_REL_NS)['id'];
            $target = ltrim((string) ($relationshipTargets[$id] ?? ''), '/');
            if (str_starts_with($target, 'xl/')) $target = substr($target, 3);
            if (!preg_match('~^worksheets/sheet\d+\.xml$~D', $target)) throw new RuntimeException('Lokasi sheet Excel tidak valid.');
            if (isset($paths[$name])) throw new RuntimeException('Sheet '.$name.' duplikat.');
            $paths[$name] = 'xl/'.$target;
        }
        return $paths;
    }

    /** @return array<string,array{value:string,type:string,formula:bool}> */
    private function sheetCells(ZipArchive $zip, string $path, array $strings): array
    {
        $sheet = $this->xml($zip, $path);
        $sheet->registerXPathNamespace('s', self::NS);
        $nodes = $sheet->xpath('//s:sheetData/s:row/s:c');
        if (count($nodes) > 200000) throw new RuntimeException('Jumlah sel Excel terlalu besar.');
        $cells = [];
        foreach ($nodes as $node) {
            $address = (string) $node['r'];
            if (!preg_match('/^[A-Z]{1,3}[1-9]\d{0,5}$/D', $address) || isset($cells[$address])) throw new RuntimeException('Alamat sel Excel tidak valid.');
            $content = $node->children(self::NS);
            $type = (string) $node['t'];
            $value = isset($content->v) ? (string) $content->v : '';
            if ($type === 's') {
                if (!ctype_digit($value) || !isset($strings[(int) $value])) throw new RuntimeException('Teks Excel tidak valid pada '.$address.'.');
                $value = $strings[(int) $value];
            } elseif ($type === 'inlineStr') {
                $node->registerXPathNamespace('s', self::NS);
                $value = implode('', array_map('strval', $node->xpath('.//s:is//s:t')));
            }
            $cells[$address] = ['value' => $value, 'type' => $type, 'formula' => isset($content->f)];
        }
        return $cells;
    }

    /** @return list<string> */
    private function sharedStrings(ZipArchive $zip): array
    {
        if ($zip->locateName('xl/sharedStrings.xml') === false) return [];
        $shared = $this->xml($zip, 'xl/sharedStrings.xml');
        $shared->registerXPathNamespace('s', self::NS);
        $strings = [];
        foreach ($shared->xpath('//s:si') as $item) {
            $item->registerXPathNamespace('s', self::NS);
            $strings[] = implode('', array_map('strval', $item->xpath('.//s:t')));
        }
        return $strings;
    }

    private function validateArchive(ZipArchive $zip): void
    {
        if ($zip->numFiles > 500) throw new RuntimeException('Struktur Excel terlalu besar.');
        $expanded = 0;
        for ($index = 0; $index < $zip->numFiles; $index++) {
            $entry = $zip->statIndex($index);
            $expanded += (int) $entry['size'];
            $printer = preg_match('~^xl/printerSettings/printerSettings\d+\.bin$~D', (string) $entry['name']);
            if ($expanded > 50 * 1024 * 1024 || preg_match('~externalLinks/|vbaProject~i', (string) $entry['name'])
                || (preg_match('~\.bin$~i', (string) $entry['name']) && !$printer)) {
                throw new RuntimeException('Excel terlalu besar, mengandung makro, atau tautan eksternal.');
            }
        }
    }

    private function xml(ZipArchive $zip, string $path): SimpleXMLElement
    {
        $raw = $zip->getFromName($path);
        if ($raw === false || $raw === '') throw new RuntimeException('Bagian Excel '.$path.' tidak ditemukan.');
        $previous = libxml_use_internal_errors(true);
        try {
            $xml = simplexml_load_string($raw, SimpleXMLElement::class, LIBXML_NONET | LIBXML_NOCDATA);
            if (!$xml instanceof SimpleXMLElement) throw new RuntimeException('XML Excel tidak valid.');
            return $xml;
        } finally { libxml_clear_errors(); libxml_use_internal_errors($previous); }
    }

    private static function monthName(int $month): string
    {
        return [1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'][$month] ?? 'Tidak valid';
    }
}
